"""onlineticketcounter URL Configuration
The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.1/topics/http/urls/
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView
from . import settings
from bus.views import PopularRoutesListView
from django.contrib.auth.decorators import login_required
from bus import views
from bus import Hodviews, Staffviews, Customerviews, Rootviews
from django.views.decorators.csrf import csrf_exempt
from django.conf.urls.static import static
from inventory import InventoryViews
from accounts import accountsviews
urlpatterns = [
     path('admin/', admin.site.urls),
     path('', views.index, name="index"),


     path('seats', views.seats_plan, name="seats"),
     path('schedule', views.schedule, name='schedule'),
     #     path('search_bus/', views.search_bus, name='search_bus'),

     path('demo', views.showDemoPage),
     path('signup_admin', views.signup_admin, name="signup_admin"),
     path('signup_customer', views.signup_customer, name="signup_customer"),
     path('signup_user', views.signup_user, name="signup_user"),
     path('do_admin_signup', views.do_admin_signup, name="do_admin_signup"),
     path('do_user_signup', views.do_user_signup, name="do_user_signup"),
     path('do_signup_customer', views.do_signup_customer, name="do_signup_customer"),
     path('admin/', admin.site.urls),
     path('results/', views.search_results, name='results'),
     path('show_login', views.ShowLoginPage, name="show_login"),
     path('show_login_user', views.ShowLoginPageuser, name="show_login_user"),
     path('get_user_details', views.GetUserDetails),
     path('logout_user', views.logout_user, name="logout"),
     path('doLogin', views.doLogin, name="do_login"),
     path('admin_home', Hodviews.admin_home, name="admin_home"),
     path('bookings/', Hodviews.booking_list, name='booking_list'),
     path('coach_details_by_date/<str:journey_date_str>/',
          Hodviews.coach_details_by_date, name='coach_details_by_date'),
     path('seat-view/<str:bus_number>/<str:coach_number>/<str:journey_date>/<int:route_id>/<str:start_point>/<str:end_point>/',
          Hodviews.views_seat, name='seat_view'),
     path('admin_home_data/', Hodviews.admin_home_data,
          name='admin_home_data'),   # added by Ajay
     path('manage_staff', Hodviews.manage_staff,
          name="manage_staff"),              # added by Ajay

     path('feedbacks/', Hodviews.feedback_list, name='feedback_list'),
     path('feedbacks/<int:feedback_id>/delete/',
          Hodviews.feedback_delete, name='feedback_delete'),
     path('staff/edit/<int:staff_id>/', Hodviews.edit_staff, name='edit_staff'),
     path('delete_staff/<int:staff_id>/',
          Hodviews.delete_staff, name='delete_staff'),
     path('suspend_company/<int:company_id>/',
          Rootviews.suspend_company, name='suspend_company'),

     path('bookings/<int:pk>/edit/',  Hodviews.booking_edit, name='booking_edit'),
     path('bookings/<int:pk>/delete/',
          Hodviews.booking_delete, name='booking_delete'),
     # path('verify/otp/', views.verify_otp, name='verify_otp'),
     path('check_existing_email', views.check_existing_email,
          name='check_existing_email'),
     path('check_existing_phone', views.check_existing_phone,
          name='check_existing_phone'),
     path('otp_verification_Signup', views.otp_verification_Signup,
          name='otp_verification_Signup'),
           path('pay-now/<int:booking_id>/', views.pay_now, name='pay_now'),
     path('add-coach/',  Hodviews.add_coach, name='add_coach'),
     path('add_staff', Hodviews.add_staff, name="add_staff"),
     path('busregi', login_required(Hodviews.busregi), name='busregi'),
     path('add_staff_save', Hodviews.add_staff_save, name="add_staff_save"),
     path('add_counter_save/', Hodviews.add_counter_save, name='add_counter_save'),
     path('add_counter', Hodviews.add_counter, name='add_counter'),
     path('counter_details/<int:counter_id>/',
          Hodviews.counter_details, name='counter_details'),
     path('add_faq_save', Hodviews.add_faq_save, name='add_faq_save'),
     path('add_faq', Hodviews.add_faq, name='add_faq'),
     path('edit/<int:faq_id>/', Hodviews.edit_faq, name='edit_faq'),
     path('delete/<int:faq_id>/', Hodviews.delete_faq, name='delete_faq'),
     path('faq_list/', Hodviews.faq_list, name='faq_list'),
     path('add_category_save', Hodviews.add_category_save, name='add_category_save'),
     path('add_category', Hodviews.add_category, name='add_category'),
     path('add_district_save', Hodviews.add_district_save, name='add_district_save'),
     path('add_district', Hodviews.add_district, name='add_district'),
     path('manage_counters', Hodviews.manage_counters, name='manage_counters'),
     path('edit_counter/<int:counter_id>/',
          Hodviews.edit_counter, name='edit_counter'),
     path('delete_counter/<int:counter_id>/',  Hodviews.delete_counter,
          name='delete_counter'),  # Add this line
     # path('add_customer', Hodviews.add_customer, name="add_student"),
     # path('add_student_save', Hodviews.add_customer_save, name="add_student_save"),
     path('get_boarding_points/', Hodviews.get_boarding_points,
          name='get_boarding_points'),
     path('get_coach_route_price/', Hodviews.get_coach_route_price,
          name='get_coach_route_price'),
     path('thanas/', Hodviews.thanas, name='thanas'),
     path('coach_save/', Hodviews.coach_save, name='coach_save'),
     path('manage-coach/', Hodviews.manage_coach, name='manage_coach'),
     path('edit_coach/<int:coach_id>/', Hodviews.edit_coach, name='edit_coach'),
     path('delete_coach/<int:coach_id>/',
          Hodviews.delete_coach, name='delete_coach'),
     path('coach_detail/', Hodviews.coach_detail, name='coach_detail'),
     path('manage/coach/<int:coach_id>/view/',
          Hodviews.manage_coach_view, name='manage_coach_view'),
     path('manage/coach/<int:coach_id>/journey_date/<int:journey_date_id>/seat_booking_details/',
          Hodviews.seat_booking_details, name='seat_booking_details'),
     path('coach_detail/', Hodviews.coach_detail, name='coach_detail'),
     path('update_coach_journey_dates/', Hodviews.update_coach_journey_dates,
          name='update_coach_journey_dates'),
     path('update_each_journey_date/', Hodviews.update_each_journey_date,
          name='update_each_journey_date'),
     path('view_coach_details/', Hodviews.view_coach_details,
          name='view_coach_details'),

     path('booking-activity/', Hodviews.booking_activity, name='booking_activity'),

     path('check_email_exist', Hodviews.check_email_exist, name="check_email_exist"),
     path('check_username_exist', Hodviews.check_username_exist,
          name="check_username_exist"),
     #     path('bus_detail/', Hodviews.bus_detail, name='bus_detail'),
     path('check_phone_number_exist', Hodviews.check_phone_number_exist,
          name="check_phone_number_exist"),
     path('district/', Hodviews.districts, name='districts'),
     path('upazilas/', Hodviews.upazilas, name='upazilas'),
     path('unions/', Hodviews.unions, name='unions'),
     # Popular Routes
     #     path('result/<str:start_point>/<str:end_point>/',
     #          views.d_t_c_result, name='result'),
     #     Staff URL Path

     path('staff_home', Staffviews.staff_home, name="staff_home"),
     path('ticket', Staffviews.ticket_booking, name="ticket"),
     path('get_customer_data/', Hodviews.get_customer_data,
          name='get_customer_data'),
     path('user_account_settings/', Hodviews.user_account_settings,
          name='user_account_settings'),
     # path('customer_home',   Customerviews.customer_home, name="customer_home"),

     # path('Customer_profile', Customerviews.student_profile, name="customer_profile"),

     path('testurl/', views.Testurl),
     # Routes ALL
     path('popularroutes', views.popular, name='popularroutes'),
     # path('counter_list/<str:district>/',
     #      views.counter_list, name='counter_lists'),
     # path('counters/<int:district_id>/', views.counter_list, name='counter_list'),
     # path('counters/<int:district_id>/json/',
     #      views.counter_list_json, name='counter_list_json'),
     path('district_list/', views.district_list, name='district_list'),
     path('district/<int:district_id>/counters/',
          views.counter_list, name='counter_list'),
     path('counter/<int:pk>/', views.counter_detail, name='counter_detail'),

     path('routes/', views.PopularRoutesListView.as_view(),
          name='routes'),

     path('add_route/', Hodviews.add_route, name='add_route'),
     path('manage_routes/', Hodviews.manage_routes, name='manage_routes'),
     path('edit_route/<int:route_id>/', Hodviews.edit_route, name='edit_route'),
     path('delete_route/<int:route_id>/',
          Hodviews.delete_route, name='delete_route'),



     path('about/', views.about, name='about'),
     path('forget_password', views.forget_password, name='forget_password'),
     path('contact/', views.contact, name='contact'),
     path('otp_verification', views.otp_verification, name='otp_verification'),
     path('reset_password/<phone_number>',
          views.reset_password, name='reset_password'),

     path('profile', views.proflepage, name='profile'),
     path('faq/', views.faq_page, name='faq'),
     path('terms/', views.terms_and_conditions, name='terms'),
     path('dashboard/', views.dashboard, name='dashboard'),
     path('complanints/', views.complanints, name='complanints'),
     path("cancelticket/", views.cancelticket, name="cancelticket"),

     path('popupseat/<str:bus_number>/<str:coach_number>/<str:journey_date>/<int:route_id>/<str:start_point>/<str:end_point>/',
          views.popup_seat_view, name='popup_seat_view'),
     path('popupseathod/<str:bus_number>/<str:coach_number>/<str:journey_date>/<int:route_id>/<str:start_point>/<str:end_point>/',
          Hodviews.popup_seat_view_hod, name='popup_seat_view'),
     path('booking/<str:bus_number>/<str:coach_number>/<str:journey_date>/<int:route_id>/<int:route_part_id>/',
          views.booking, name='booking'),

     path('booking_hod/<str:bus_number>/<str:coach_number>/<str:journey_date>/<int:route_id>/<int:route_part_id>/',
          Hodviews.booking_hod, name='booking_hod'),

     path('search_booking/', views.search_booking, name='search_booking'),
     path('cacelationpolicy/', views.cacelationpolicy, name='cacelationpolicy'),
     path('privacypolicy/', views.privacypolicy, name='privacypolicy'),
     path('insurance/', views.insurance, name='insurance'),
     path('insurance_term/', views.insurance_term, name='insurance_term'),
     path('admin_profile', Hodviews.admin_profile, name="admin_profile"),
     path('admin_profile_save', Hodviews.admin_profile_save,
          name="admin_profile_save"),
     path('add-facilities/',  Hodviews.add_facilities, name='add_facilities'),
     path('edit-facility/<int:facility_id>/',
          Hodviews.edit_facility, name='edit_facility'),
     path('delete-facility/<int:facility_id>/',
          Hodviews.delete_facility, name='delete_facility'),
     path('manage-facilities/',  Hodviews.manage_facilities,
          name='manage_facilities'),
     path('search_form/',  Hodviews.search_form,
          name='search_form'),
     path('create_user/', Hodviews.create_user, name='create_user'),
     path('user_list/', Hodviews.user_list, name='user_list'),
     path('update_user/<int:user_id>/',  Hodviews.update_user, name='update_user'),
     path('delete_user/<int:user_id>/',  Hodviews.delete_user, name='delete_user'),
     path('user_detail/<int:user_id>/', Hodviews.user_detail, name='user_detail'),

     path('customers/', Hodviews.customer_list, name='customer_list'),
     path('customers/add/', Hodviews.add_customer, name='add_customer'),
     path('customers/edit/<int:pk>/', Hodviews.edit_customer, name='edit_customer'),
     path('customers/delete/<int:pk>/',
          Hodviews.delete_customer, name='delete_customer'),


     path('staff-types/', Hodviews.staff_type_list, name='staff_type_list'),
     path('staff-types/add/', Hodviews.add_staff_type, name='add_staff_type'),
     path('staff-types/<str:name>/',
          Hodviews.edit_staff_type, name='edit_staff_type'),
     path('staff-types/<str:name>/delete/',
          Hodviews.delete_staff_type, name='delete_staff_type'),
     path('assign_staff_type/',
          Hodviews.assign_staff_type, name='assign_staff_type'),
     path('manage_assigned_staff/', Hodviews.manage_assigned_staff,
          name='manage_assigned_staff'),
     path('assign_staff_details/<int:staff_id>/',
          Hodviews.assign_staff_details, name='assign_staff_details'),
     path('delete_staff_assigned/<int:staff_id>/',
          Hodviews.delete_staff_type, name='delete_staff_assigned'),
     path('add_vehicle/', Hodviews.add_vehicle, name='add_vehicle'),
     path('vehicle_list/', Hodviews.vehicle_list, name='vehicle_list'),
     path('edit_vehicle/<int:vehicle_id>/',
          Hodviews.edit_vehicle, name='edit_vehicle'),
     path('delete_vehicle/<int:vehicle_id>/',
          Hodviews.delete_vehicle, name='delete_vehicle'),
     path('bus_stop/list/', Hodviews.bus_stop_list, name='bus_stop_list'),
     path('bus_stop/add/', Hodviews.add_bus_stop, name='add_bus_stop'),
     path('bus_stop/edit/<int:pk>/', Hodviews.edit_bus_stop, name='edit_bus_stop'),
     path('bus_stop/delete/<int:pk>/',
          Hodviews.delete_bus_stop, name='delete_bus_stop'),
     path('tax/list/', Hodviews.tax_list, name='tax_list'),
     path('tax/add/', Hodviews.add_tax, name='add_tax'),
     path('tax/edit/<int:tax_id>/', Hodviews.edit_tax, name='edit_tax'),
     path('delete_tax/<int:tax_id>/', Hodviews.delete_tax, name='delete_tax'),
     path('payment_method/', Hodviews.payment_method_list,
          name='payment_method_list'),
     path('payment_method/add/', Hodviews.add_payment_method,
          name='add_payment_method'),
     path('payment_method/<int:pk>/edit/',
          Hodviews.edit_payment_method, name='edit_payment_method'),
     path('payment_method/<int:pk>/delete/',
          Hodviews.delete_payment_method, name='delete_payment_method'),
     path('staff_booking_data/',
          Hodviews.staff_booking_data, name='staff_booking_data'),
     path('route_booking_count_graph/', Hodviews.route_booking_count_graph,
          name='route_booking_count_graph'),
     path('payment_method_booking_count/', Hodviews.payment_method_booking_count,
          name='payment_method_booking_count'),
     path('assign_permissions/<int:user_id>/',
          Hodviews.assign_permissions, name='assign_permissions'),

     path('bus-fitness/add/', Hodviews.add_bus_fitness, name='add_bus_fitness'),
     path('bus-fitness/list/', Hodviews.fitness_list, name='fitness_list'),
     path('bus-fitness/edit/<int:fitness_id>/',
          Hodviews.edit_bus_fitness, name='edit_bus_fitness'),
     path('bus-fitness/delete/<int:fitness_id>/',
          Hodviews.delete_bus_fitness, name='delete_bus_fitness'),
     path('cancelticket_hod', Hodviews.cancelticket_hod, name='cancelticket_hod'),
     path('approve_cancel_request/<int:cancel_ticket_id>/',
          Hodviews.approve_cancel_request, name='approve_cancel_request'),
     path('reject_cancel_request/<int:cancel_ticket_id>/',
          Hodviews.reject_cancel_request, name='reject_cancel_request'),

     path('booking_popup_time',
          Hodviews.booking_popup_time, name='booking_popup_time'),

     path('my_ticket_list/', views.my_ticket_list, name='my_ticket_list'),
     path("my_ticket_details/<str:booking_id>/",
          views.my_ticket_details, name="my_ticket_details"),
     path('set_popup_time/',  Hodviews.set_popup_time, name='set_popup_time'),
     path('all-bookings/', Hodviews.all_bookings, name='all_bookings'),
     path('cancel_booking/<int:booking_id>/',
          Hodviews.cancel_booking, name='cancel_booking'),
     path('make_payment/<int:booking_id>/',
          Hodviews.make_payment, name='make_payment'),
     path(
          'print_ticket_pdf/<str:journey_date>/<str:coach_number>/<str:seat_number>/<str:price>/<str:pnr>/<str:user_name>/<int:booking_id>/',
          Hodviews.print_ticket_pdf,
          name='print_ticket_pdf',
     ),
        path('delete_bus/<int:bus_id>/',
         Hodviews.delete_bus, name='delete_bus'),


  path('view_vehicle/<int:vehicle_id>/', Hodviews.view_vehicle, name='view_vehicle'),

     path('view_invoice/<int:booking_id>/',
          Hodviews.view_invoice, name='view_invoice'),
     path('refund_booking/<int:booking_id>/',
          Hodviews.refund_booking, name='refund_booking'),
     path('payment_details/<int:booking_id>/',
          Hodviews.payment_details, name='payment_details'),
     path('payment_details/<int:booking_id>/',
          Hodviews.payment_details, name='payment_details'),
     path('pos-invoice/<int:booking_id>/',
          Hodviews.pos_invoice_view, name='pos_invoice_view'),
          
     path('approved_cancel_tickets/', Hodviews.approved_cancel_tickets_view,
          name='approved_cancel_tickets'),
     path('refund-list/', Hodviews.refund_list, name='refund_list'),
     path('bus_list/',Hodviews.bus_list,name="bus_list"),
    
     #     path('create_company/', Hodviews.create_company, name='create_company'),
     #     path('register_user/<int:company_id>/',
     #          Hodviews.register_user, name='register_user'),
     path('root_home/', Rootviews.root_home, name='root_home'),
     path('create_company', Rootviews.create_company, name='create_company'),
     path('company_list', Rootviews.company_list, name='company_list'),


     path('staff_types/', Rootviews.staff_type_list, name='staff_type_list'),
     path('staff_types/create/', Rootviews.create_staff_type,
          name='create_staff_type'),
     path('staff-types/<str:name>/', Rootviews.edit_staff_type_root,
          name='edit_staff_type_root'),
     path('staff_types/delete/<str:name>/',
          Rootviews.delete_staff_type_root, name='delete_staff_type_root'),
     path('staff_types/delete/<str:name>/',
          Rootviews.delete_staff_type_root, name='delete_staff_type_root'),
     path('companies/<str:company_id>/assign-staff-type/',
          Rootviews.assign_staff_type, name='assign_staff_type'),


     path('assigned_staff_types/',
          Rootviews.assigned_staff_types_list, name='assigned_staff_types_list'),

    path('<str:company_id>/assigned-staff-type/edit/', Rootviews.assigned_staff_type_edit, name='assigned_staff_type_edit'),
    path('dashboard_root/',Rootviews.dashboard,name="dashboard_root"),

     # Inventory Part
 path('inventory/home/', InventoryViews.inventory_home, name='inventory_home'),
    path('add_subcategory/', InventoryViews.add_subcategory, name='add_subcategory'),
    path('list_brands/', InventoryViews.list_and_add_brands, name='list_brands'),
    path('edit_brand/<int:brand_id>/',
         InventoryViews.edit_brand, name='edit_brand'),
    path('delete_brand/<int:brand_id>/',
         InventoryViews.delete_brand, name='delete_brand'),


    path('list_unit/', InventoryViews.list_and_add_units, name='list_unit'),
    path('edit_unit/<int:unit_id>/', InventoryViews.edit_unit, name='edit_unit'),
    path('delete_unit/<int:unit_id>/',
         InventoryViews.delete_unit, name='delete_unit'),
    path('add_item/', InventoryViews.add_item, name='add_item'),
    path('product_list/', InventoryViews.product_list, name='product_list'),
    path('edit_product/<int:product_id>/',
         InventoryViews.edit_product, name='edit_product'),
    path('delete_product/<int:product_id>/',
         InventoryViews.delete_product, name='delete_product'),
    path('add_inventory_adjustment/', InventoryViews.add_inventory_adjustment,
         name='add_inventory_adjustment'),
  path('get_adjustment_products_by_warehouse_for_purchase/<int:warehouse_id>/', InventoryViews.get_adjustment_products_by_warehouse_for_purchase, name='get_adjustment_products_by_warehouse_for_purchase'),
    path('get_adjustment_product_details_for_purchase/', InventoryViews.get_adjustment_product_details_for_purchase, name='get_adjustment_product_details_for_purchase'),
    path('save_adjustment/',InventoryViews.save_adjustment,name="save_adjustment"),
     path('adjustment_list/', InventoryViews.adjustment_list, name='adjustment_list'),
      path('view_adjustment/<int:adjustment_id>/', InventoryViews.view_adjustment, name='view_adjustment'),
     path('delete_adjustment/<int:adjustment_id>/',InventoryViews.delete_adjustment,name="delete_adjustment"),

    # People

    path('add_biller/', InventoryViews.add_biller, name='add_biller'),
    path('biller_list/', InventoryViews.biller_list, name='biller_list'),

    path('edit_biller/<int:biller_id>/',
         InventoryViews.edit_biller, name='edit_biller'),
    path('delete_biller/<int:biller_id>/',
         InventoryViews.delete_biller, name='delete_biller'),

    path('add_supplier/', InventoryViews.add_supplier, name='add_supplier'),

    path('supplier_list/', InventoryViews.supplier_list, name='supplier_list'),

    path('edit_supplier/<int:supplier_id>/',
         InventoryViews.edit_supplier, name='edit_supplier'),
    path('delete_supplier/<int:supplier_id>/',
         InventoryViews.delete_supplier, name='delete_supplier'),
    # People
    path('warehouse_list/', InventoryViews.warehouse_list, name='warehouse_list'),
    path('add_warehouse/', InventoryViews.add_warehouse, name='add_warehouse'),
    path('edit_warehouse/<int:warehouse_id>/',
         InventoryViews.edit_warehouse, name='edit_warehouse'),
    path('delete_warehouse/<int:warehouse_id>/',
         InventoryViews.delete_warehouse, name='delete_warehouse'),
    path('add_transfer/', InventoryViews.add_transfer, name='add_transfer'),
    path('get_product_details/', InventoryViews.get_product_details,
         name='get_product_details'),
    path('add_purchase/', InventoryViews.add_purchase, name='add_purchase'),
    path('get_products_by_warehouse/<int:warehouse_id>/',
         InventoryViews.get_products_by_warehouse, name='get_products_by_warehouse'),
    path('purchase_list/', InventoryViews.purchase_list, name='purchase_list'),
    path('make_payment_inventory/<int:purchase_id>/',
         InventoryViews.make_payment_inventory, name='make_payment_inventory'),
    path('get_payment_data/<int:purchase_id>/',
         InventoryViews.get_payment_data, name='get_payment_data'),
    path('edit_payment/<int:purchase_id>/',
         InventoryViews.edit_payment, name='edit_payment'),

    # Define the URL for deleting a payment
    path('delete_payment/<int:payment_id>/',
         InventoryViews.delete_payment, name='delete_payment'),

    path('view_purchase/<int:purchase_id>/',
         InventoryViews.view_purchase, name='view_purchase'),

    # Define the URL for editing a purchase
    path('edit_purchase/<int:purchase_id>/',
         InventoryViews.edit_purchase, name='edit_purchase'),
    path('delete_purchase/<int:purchase_id>/',
         InventoryViews.delete_purchase, name='delete_purchase'),
    path('add_purchase_return/', InventoryViews.create_purchase_return,
         name='add_purchase_return'),
    path('purchase_return_list/', InventoryViews.purchase_return_list,
         name='purchase_return_list'),

    path('get_warehouses/<int:supplier_id>/',
         InventoryViews.get_related_warehouses, name='get_warehouses'),
    path('get_purchases/<int:supplier_id>/<int:warehouse_id>/',
         InventoryViews.get_purchases, name='get_purchases'),
    path('edit_purchase_return/<int:return_id>/',
         InventoryViews.view_purchase_return_json, name='edit_purchase_return'),
    path('delete_purchase_return/<int:return_id>/',
         InventoryViews.delete_purchase_return, name='delete_purchase_return'),

    # URL pattern for viewing purchase return details as JSON
    path('view_purchase_return_json/<int:return_id>/',
         InventoryViews.view_purchase_return_json, name='view_purchase_return_json'),
    path('generate_purchase_report/', InventoryViews.generate_purchase_report,
         name='generate_purchase_report'),
    path('generate_pdf_report/', InventoryViews.generate_pdf_report,
         name='generate_pdf_report'),
    path('api/purchases/', InventoryViews.filter_purchase_report,
         name='filter_purchase_report'),

    path('generate_payment_report/', InventoryViews.generate_payment_report,
         name='generate_payment_report'),
    path('generate_pdf_report_payment/', InventoryViews.generate_pdf_report_payment,
         name='generate_pdf_report_payment'),
    path('api/payments/', InventoryViews.filter_payment_report_payment,
         name='filter_payment_report_payment'),
     path('generate_product_report/', InventoryViews.generate_product_report,
         name='generate_product_report'),
    path('generate_pdf_report_product/', InventoryViews.generate_pdf_report_product,
         name='generate_pdf_report_product'),
    path('api/product/', InventoryViews.filter_product_report,
         name='filter_product_report'),

     path('generate_warehouse_report/', InventoryViews.generate_warehouse_report,
         name='generate_warehouse_report'),
    path('generate_pdf_report_warehouse/', InventoryViews.generate_pdf_report_warehouse,
         name='generate_pdf_report_warehouse'),
    path('api/warehouses/', InventoryViews.filter_warehouse_report,
         name='filter_warehouse_report'),
     path('add_subcategory_expense/', InventoryViews.add_subcategory_expense, name='add_subcategory_expense'),
     path('add_expense/',InventoryViews.add_expense,name='add_expense'),
     path('expense_list/',InventoryViews.expense_list,name="expense_list"),
     path('delete_expense/<int:expense_id>/',InventoryViews.delete_expense,name='delete_expense'),
     path('make_payment_expense/<int:expense_id>/',
          InventoryViews.make_payment_expense, name='make_payment_expense'),
     path('get_payment_data_expense/<int:expense_id>/',InventoryViews.get_payment_data_expense, name='get_payment_data_expense'),
     path('add_payment_expense/',InventoryViews.add_payment_expense,name='add_payment_expense'),

         
    path('generate_supplier_report/', InventoryViews.generate_supplier_report,
         name='generate_supplier_report'),
    path('generate_pdf_report_supplier/', InventoryViews.generate_pdf_report_supplier,
         name='generate_pdf_report_supplier'),
    path('api/suppliers/', InventoryViews.filter_supplier_report,
         name='filter_supplier_report'),
             path('transferlist/', InventoryViews.transferlist,
         name='transferlist'),

    path('save_transfer/', InventoryViews.save_transfer, name='save_transfer'),
    path('stock_report/', InventoryViews.stock_report, name='stock_report'),
    path('product_installation/', InventoryViews.product_installation, name='product_installation'),
    path('save_product_installation/', InventoryViews.save_product_installation, name='save_product_installation'),
    path('products_usage_list/', InventoryViews.products_usage_list, name='products_usage_list'),
    path('save_purchase/', InventoryViews.save_purchase, name='save_purchase'),
    path('get_products_by_warehouse_for_purchase/<int:warehouse_id>/', InventoryViews.get_products_by_warehouse_for_purchase, name='get_products_by_warehouse_for_purchase'),
    path('get_product_details_for_purchase/', InventoryViews.get_product_details_for_purchase, name='get_product_details_for_purchase'),
    path('purchase_invoice/', InventoryViews.purchase_invoice, name='purchase_invoice'),
    path('save_purchase_invoice/', InventoryViews.save_purchase_invoice, name='save_purchase_invoice'),
    path('dashboard_inventory/', InventoryViews.dashboard, name='dashboard_inventory'),
    path('stock_data/',InventoryViews.stock_data,name='stock_data'),
    path('top_suppliers/',InventoryViews.top_suppliers,name="top_suppliers"),
    path('top_billers/',InventoryViews.top_billers,name="top_billers"),
    path('combined_table_inventory/', InventoryViews.combined_table_inventory,name='combined_table_inventory'),
     # end of Inventory Part

     # Accounts Part start in there 
     path('add_bank/', accountsviews.add_bank, name='add_bank'),
     path('bank_list/',accountsviews.bank_list,name='bank_list'),
     path('edit_bank/<int:bank_id>/', accountsviews.edit_bank, name='edit_bank'),
     path('delete_bank/<int:bank_id>/', accountsviews.delete_bank, name='delete_bank'),
     path('create_balance_transfer/',accountsviews.create_balance_transfer,name='create_balance_transfer'),
     path('transfer_list/',accountsviews.transfer_list,name="transfer_list"),
     path('edit_transfer/<int:transfer_id>/', accountsviews.edit_transfer, name='edit_transfer'),
     path('delete_transfer/<int:transfer_id>/', accountsviews.delete_transfer, name='delete_transfer'),
     path('add_transaction/',accountsviews.add_transaction,name="add_transaction"),
     path('add_payment_invoice/',accountsviews.add_payment_invoice,name="add_payment_invoice"),
     path('financial_transaction_list/',accountsviews.financial_transaction_list,name='financial_transaction_list'),
     path('edit_transaction/<int:transaction_id>/', accountsviews.edit_transaction, name='edit_transaction'),
     path('delete_transaction/<int:transaction_id>/', accountsviews.delete_transaction, name='delete_transaction'),
     path('edit_payment_invoice/<int:invoice_id>/', accountsviews.edit_payment_invoice, name='edit_payment_invoice'),
     path('delete_invoice/<int:invoice_id>/', accountsviews.delete_invoice, name='delete_invoice'),
     path('payment_invoice_list/',accountsviews.payment_invoice_list,name='payment_invoice_list'),
     path('create_credit_voucher/',accountsviews.create_credit_voucher,name='create_credit_voucher'),
     path('credit_voucher_list/',accountsviews.credit_voucher_list,name='credit_voucher_list'),
     path('create_debit_voucher/',accountsviews.create_debit_voucher,name='create_debit_voucher'),
     path('debit_voucher_list/',accountsviews.debit_voucher_list,name='debit_voucher_list'),
     path('get_expense_details/<int:invoice_id>/', accountsviews.get_expense_details, name='get_expense_details'),
     path('create_bill/',accountsviews.create_bill,name='create_bill'),
     path('total_transactions/', accountsviews.total_transactions, name='total_transactions'),
     path('assign_bank/<int:bank_id>/', accountsviews.assign_bank, name='assign_bank'),
     path('total_expense/', accountsviews.expense, name='total_expense'),
     path('revenue_view/', accountsviews.revenue_view, name='revenue_view'),
     path('income_vs_expense/', accountsviews.income_vs_expense, name='income_vs_expense'),
     path('profit_loss/', accountsviews.profit_loss, name='profit_loss'),
     path('trail_balance/',accountsviews.trail_balance,name="trail_balance"),
     path('dashboard_accounts/',accountsviews.dashboard,name="dashboard_accounts"),
     path('cash-flow-chart-data/', accountsviews.cash_flow_chart_data, name='cash-flow-chart-data'),
     path('recent_vouchers/',accountsviews.recent_vouchers,name='recent_vouchers'),
     path('counter_credit_balance/',accountsviews.counter_credit_balance,name='counter_credit_balance'),
     path('recent_bookings/',accountsviews.recent_bookings,name='recent_bookings'),
     path('income_vs_expense_json/',accountsviews.income_vs_expense_json,name='income_vs_expense_json'),
     path('active_user_list/', accountsviews.active_user_list, name='active_user_list'),
     path('supplier_list_accounts/', accountsviews.supplier_list, name='supplier_list_accounts'),
     path('biller_list_accounts/', accountsviews.biller_list, name='biller_list_accounts'),
     path('customer_list_accounts/', accountsviews.customer_list, name='customer_list_accounts'),
     path('notifications/', accountsviews.notification_list, name='notifications'),
     path('create_journal_entry/', accountsviews.create_journal_entry, name='create_journal_entry'),
     path('save_journal/', accountsviews.save_journal, name='save_journal'),
     path('journal_list/', accountsviews.journal_list, name='journal_list'),
     path('create_ledger/', accountsviews.create_ledger, name='create_ledger'),
     path('get_accounts_name/', accountsviews.get_accounts_name, name='get_accounts_name'),
     path('save_ledger/', accountsviews.save_ledger, name='save_ledger'),
     path('ledger_list/', accountsviews.ledger_list, name='ledger_list'),
     path('ledger_view/', accountsviews.ledger_view, name='ledger_view'),
     path('get_transaction_details/<int:transaction_id>/', accountsviews.get_transaction_details, name='get_transaction_details'),
     path('get_transaction_details/<int:transaction_id>/', accountsviews.get_transaction_details, name='get_transaction_details'),
     path('get_debit_voucher_details/<int:voucher_id>/', accountsviews.get_debit_voucher_details, name='get_debit_voucher_details'),
      path('get_credit_voucher_details/<int:voucher_id>/', accountsviews.get_credit_voucher_details, name='get_credit_voucher_details'),
      

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
