# Generated by Django 4.2.7 on 2023-11-25 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Bank Name')),
                ('branch', models.CharField(max_length=100, verbose_name='Branch')),
                ('account_name', models.CharField(max_length=100, verbose_name='Account Name')),
                ('account_holder', models.CharField(max_length=100, verbose_name='Account Holder')),
                ('account_no', models.CharField(max_length=20, verbose_name='Account No')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone')),
                ('initial_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Initial Balance')),
                ('internet_banking_url', models.URLField(verbose_name='Internet Banking URL')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10, verbose_name='Status')),
                ('assigned_select_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Assigned  Name')),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel_date', models.DateField()),
                ('bill_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CreditVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('payment_gateway', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=200)),
                ('payment_mode', models.CharField(max_length=100)),
                ('cheque_number', models.CharField(blank=True, max_length=20, null=True)),
                ('reference', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('particular', models.TextField()),
                ('voucher_number', models.CharField(editable=False, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DebitVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('payment_gateway', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=100, null=True)),
                ('payment_mode', models.CharField(max_length=100)),
                ('cheque_number', models.CharField(blank=True, max_length=20, null=True)),
                ('reference', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('particular', models.TextField()),
                ('voucher_number', models.CharField(editable=False, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10, verbose_name='Status')),
                ('invoice_number', models.CharField(max_length=20, verbose_name='Invoice Number')),
                ('payment_type', models.CharField(choices=[('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('check', 'Check')], max_length=20, verbose_name='Payment Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('date', models.DateField(verbose_name='Date')),
                ('reference', models.CharField(max_length=100, verbose_name='Reference')),
                ('payment_receipt', models.FileField(blank=True, null=True, upload_to='payment_receipts/', verbose_name='Payment Receipt')),
                ('payment_note', models.TextField(blank=True, verbose_name='Payment Note')),
                ('object_id', models.PositiveIntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.bank', verbose_name='Account')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Payment Invoice',
                'verbose_name_plural': 'Payment Invoices',
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10, verbose_name='Status')),
                ('voucher_number', models.CharField(max_length=20, verbose_name='Voucher Number')),
                ('payment_type', models.CharField(choices=[('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('check', 'Check')], max_length=20, verbose_name='Payment Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('date', models.DateField(verbose_name='Date')),
                ('reference', models.CharField(max_length=100, verbose_name='Reference')),
                ('payment_receipt', models.FileField(blank=True, null=True, upload_to='payment_receipts/', verbose_name='Payment Receipt')),
                ('payment_note', models.TextField(blank=True, verbose_name='Payment Note')),
                ('object_id', models.PositiveIntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.bank', verbose_name='Account')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Financial Transaction',
                'verbose_name_plural': 'Financial Transactions',
            },
        ),
    ]
