# Generated by Django 4.2.7 on 2023-11-25 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bus', '0001_initial'),
        ('accounts', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='counter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bus.counter', verbose_name='Counter'),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier', verbose_name='Supplier'),
        ),
        migrations.AddField(
            model_name='debitvoucher',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_vouchers', to='accounts.bank'),
        ),
        migrations.AddField(
            model_name='creditvoucher',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_vouchers', to='accounts.bank'),
        ),
        migrations.AddField(
            model_name='bill',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bus.booking'),
        ),
        migrations.AddField(
            model_name='bill',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.staffs'),
        ),
        migrations.AddField(
            model_name='balancetransfer',
            name='from_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='accounts.bank'),
        ),
        migrations.AddField(
            model_name='balancetransfer',
            name='to_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='accounts.bank'),
        ),
    ]
