# Generated by Django 4.2.7 on 2023-11-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Remaining Balance'),
        ),
    ]
