# Generated by Django 4.2.7 on 2023-12-03 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_journalentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentry',
            old_name='bank',
            new_name='account',
        ),
    ]
