# Generated by Django 4.2.7 on 2023-12-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_biller_account_name_biller_bank_account_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='order_discount',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
