# Generated by Django 4.2.7 on 2023-12-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_purchase_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='order_tax',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
