# Generated by Django 4.2.7 on 2023-12-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_counter_bank_account_no_counter_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
